# Automatically mount Windows drive when the distribution is launched
[automount]
enabled=true
mountFsTab=false

[network]
#hostname=DemoHost
#generateHosts=true
#generateResolvConf=true

[interop]
enabled=true
appendWindowsPath=false

[user]
default=quangl

[boot]
systemd=true

[gpu]
enabled=true

[time]
useWindowsTimezone=true