name: Update pre-commit hooks

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6

      - name: Run pre-commit autoupdate
        run: pipx run pre-commit autoupdate

      - id: create-pull-request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          branch: update-pre-commit-hooks
          delete-branch: true

      - name: Auto-merge
        if: steps.create-pull-request.outputs.pull-request-number
        run: gh pr merge "$PR_NUMBER" --auto --squash
        env:
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
